### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by kill4n** [OpenDatacubeIDEAM/cdcol-web#8]
Al intentar crear un algoritmo en el ambiente de pruebas y actualizar la versión me genero una pagina con **500 ERROR INTERNO**, a continuación se encuentra el resultado del comando  "sudo journalctl -u gunicorn.service"

```sep 15 09:44:19 test-cubo-web gunicorn[1117]: Traceback (most recent call last):
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/v_ideam/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     response = get_response(request)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/v_ideam/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     response = self.process_exception_by_middleware(e, request)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/v_ideam/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/v_ideam/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     return self.dispatch(request, *args, **kwargs)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/v_ideam/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     return bound_method(*args, **kwargs)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/v_ideam/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     return view_func(request, *args, **kwargs)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/v_ideam/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     return super().dispatch(request, *args, **kwargs)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/v_ideam/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     return handler(request, *args, **kwargs)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/v_ideam/lib/python3.6/site-packages/django/views/generic/edit.py", line 194, in post
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     return super().post(request, *args, **kwargs)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/v_ideam/lib/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     return self.form_valid(form)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/projects/web-app/algorithm/views.py", line 299, in form_valid
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     response = urllib.request.urlopen(self.object.repository_url)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/anaconda/lib/python3.6/urllib/request.py", line 223, in urlopen
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     return opener.open(url, data, timeout)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/anaconda/lib/python3.6/urllib/request.py", line 526, in open
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     response = self._open(req, data)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/anaconda/lib/python3.6/urllib/request.py", line 544, in _open
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     '_open', req)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/anaconda/lib/python3.6/urllib/request.py", line 504, in _call_chain
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     result = func(*args)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/anaconda/lib/python3.6/urllib/request.py", line 1361, in https_open
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     context=self._context, check_hostname=self._check_hostname)
sep 15 09:44:19 test-cubo-web gunicorn[1117]:   File "/home/cubo/anaconda/lib/python3.6/urllib/request.py", line 1320, in do_open
sep 15 09:44:19 test-cubo-web gunicorn[1117]:     raise URLError(err)
sep 15 09:44:19 test-cubo-web gunicorn[1117]: urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
```

**Comment by kill4n** [comment]
[Solucionado]

El problema se genero al usar urls de gitlab:
https://gitlab.virtual.uniandes.edu.co/datacube-ideam/CDCol/raw/master/algorithms/medianas/medianas_2.0.py
se deben usar urls de github para solucionarlo
https://raw.githubusercontent.com/OpenDatacubeIDEAM/cdcol/desacoplado/algorithms/medianas/medianas_2.2.py
